"""add user fields and user_dept table

Revision ID: 1b8959a9ca60
Revises: 907bba255c49
Create Date: 2026-03-24 11:01:31.253034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8959a9ca60'
down_revision: Union[str, Sequence[str], None] = '907bba255c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main_dept_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('direct_leader_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('FK__users__departmen__5AEE82B9'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('FK__users__role_id__5535A963'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['direct_leader_id'], ['id'])
    op.create_foreign_key(None, 'users', 'departments', ['main_dept_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('FK__users__role_id__5535A963'), 'users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('FK__users__departmen__5AEE82B9'), 'users', 'departments', ['department_id'], ['id'])
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'position')
    op.drop_column('users', 'direct_leader_id')
    op.drop_column('users', 'main_dept_id')
    # ### end Alembic commands ###
