"""remove main_dept

Revision ID: c1125db8b758
Revises: b1335f5d7f15
Create Date: 2026-03-25 14:40:18.177459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1125db8b758'
down_revision: Union[str, Sequence[str], None] = 'b1335f5d7f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__users__main_dept__6FE99F9F'), 'users', type_='foreignkey')
    op.drop_column('users', 'main_dept_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main_dept_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('FK__users__main_dept__6FE99F9F'), 'users', 'departments', ['main_dept_id'], ['id'])
    # ### end Alembic commands ###
