"""add role_id to users

Revision ID: de2fd451e569
Revises: 1b8959a9ca60
Create Date: 2026-03-24 11:23:18.133777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'de2fd451e569'
down_revision: Union[str, Sequence[str], None] = '1b8959a9ca60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_table('attendances')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=mssql.BIT(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'is_deleted',
               existing_type=mssql.BIT(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'is_deleted',
               existing_type=mssql.BIT(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'is_active',
               existing_type=mssql.BIT(),
               nullable=True)
    op.drop_column('users', 'role_id')
    op.create_table('attendances',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('check_out_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('FK__attendanc__user___48CFD27E')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__attendan__3213E83FBF7B0922'))
    )
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    # ### end Alembic commands ###
